# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-08-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210801_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='referral',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
